# Generated by Django 3.1.7 on 2021-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTopicStock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_rank', models.TextField()),
                ('title', models.TextField()),
                ('price', models.IntegerField()),
                ('low', models.TextField()),
                ('volume', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('buy', models.IntegerField()),
                ('sell', models.IntegerField()),
                ('capitalization', models.TextField()),
                ('per', models.TextField()),
                ('roe', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_topic_stock',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MyTopicMovie',
        ),
        migrations.DeleteModel(
            name='MyTopicUsers',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='TopicStock',
        ),
    ]
